"""empty message

Revision ID: b5117afe7530
Revises: ab1ad35f4284
Create Date: 2022-02-24 17:44:50.969825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5117afe7530'
down_revision = 'ab1ad35f4284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('threads', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('threads', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('threads', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('threads', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('threads', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('votes')
    # ### end Alembic commands ###
